services:
  recipes-test-db:
    container_name: recipes-test-db
    image: postgres:16.9-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=recipes-test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s
